## Data loading for default of credit card clients dataset 

To use the data, simply load the pickle file

In [45]:
import pickle
with open("train_test_split.pkl", "br") as fh:
    data = pickle.load(fh)
train_data = data[0]
test_data = data[1]

train_x = train_data[:,:23]
train_y = train_data[:,23] # labels are either 0 or 1
test_x = test_data[:,:23]
test_y = test_data[:,23] # labels are either 0 or 1

# converting the labels to +-1 

In [46]:
train_y = 2*train_y - 1
test_y = 2*test_y -1

In [56]:
import numpy as np
import pdb

# weak classifier

In [77]:
# h_j = sign(x_j-m_j)
def naive_weak_classifier(X,j=None):
    #X : nxd 
    #j : jth feature <=d if none then comute H_j = n*d matrix
    # return 
    # h_j = nx1 classifier or H_j  = n*d matrix  
    if j != None:
        X_j = X[:,j]
        M_j = np.median(X_j) 
        h_j_temp  = X_j - M_j
        h_j  = np.where(h_j_temp >= 0, 1, -1)[...,np.newaxis]
        return h_j
    else :
        #print(X.shape)
        M = np.median(X,axis=0)[np.newaxis,...]
        #print(M.shape) 
        H_j_temp  = X - M
        H  = np.where(H_j_temp >= 0, 1, -1)
        return H
    

In [78]:
h_j_1 = naive_weak_classifier(X=train_x,j=None)
print(h_j_1.shape)

(20000, 23)


# Parallel Ada Boost Algorithm-1

In [97]:
def adaboost(data , targets , M,w0 ,p0,max_pass=300, train_data=True):
    w_t = w0
    p_t = p0
    M_positive = np.maximum(M,0)
    M_negative = np.abs(M) - M_positive
    for i in range(max_pass):
        p_t = np.divide(p_t,np.sum(p_t))
        epsi_t = np.transpose(M_negative)@p_t 
        gamma_t = 1- epsi_t
        beta_t_temp = np.divide(gamma_t,epsi_t)
        beta_t_temp
        print("itr",i, beta_t_temp.shape)
        beta_t = 0.5*np.log(beta_t_temp)
        alpha_t = np.ones((data.shape[1],1)) # Parallel Adaboost
        w_t = w_t + np.multiply(alpha_t,beta_t)
        p_t = np.multiply(p_t,np.exp(-M@(np.multiply(alpha_t,beta_t))))
    return w_t

# calling Ada BOOST

In [98]:

H = naive_weak_classifier(X=train_x,j=None)
M = np.multiply(train_y[...,np.newaxis],H)
w_final = adaboost(train_x , train_y , M,w0 = np.zeros((train_x.shape[1],1)),p0 = np.ones((train_x.shape[0],1)),max_pass=10, train_data=True)
print(M.shape)

itr 0 (23, 1)


TypeError: loop of ufunc does not support argument 0 of type float which has no callable log method

In [90]:
tt = np.random.rand(10,1)
np.log(tt)

array([[-0.59468616],
       [-0.0970176 ],
       [-0.1869833 ],
       [-0.07071535],
       [-0.86439865],
       [-0.39109914],
       [-0.19375431],
       [-0.24069082],
       [-6.79121427],
       [-4.24468554]])

In [30]:
from numpy import random
pt = np.random.rand(4,1)
tt = np.sum(pt)
np.divide(pt,tt)

array([[0.28057797],
       [0.19381623],
       [0.51073422],
       [0.01487158]])

In [38]:
train_x[:,1]

array([1, 2, 2, ..., 1, 2, 2], dtype=object)